# Generated by Django 6.1.1 on 2026-09-25 05:26

import catalog.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m/', validators=[django.core.validators.validate_image_file_extension, catalog.validators.ProductImageValidator()]),
        ),
    ]
