# Generated by Django 6.1.1 on 2026-09-24 05:09

import orders.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_address_line_order_city_order_confirmed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('QR', 'QR Payment'), ('ESEWA', 'eSewa'), ('KHALTI', 'Khalti'), ('FONEPAY', 'FonePay'), ('IMEPAY', 'IME Pay'), ('BANK', 'Bank Transfer'), ('COD', 'Cash on Delivery')], db_index=True, default='ESEWA', max_length=12),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment_screenshots/', validators=[orders.validators.PaymentScreenshotValidator()]),
        ),
    ]
