# Generated by Django 6.1.1 on 2026-09-27 10:19

import config.storage
import orders.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='gateway_txn_id',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, storage=config.storage.PrivateMediaStorage(), upload_to='payment_screenshots/', validators=[orders.validators.PaymentScreenshotValidator()]),
        ),
    ]
